<?php

/**
 * @file
 * Contains term_condition.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function term_condition_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the term_condition module.
    case 'help.page.term_condition':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Check to see if a node references a particular taxonomy term.') . '</p>';
      return $output;

    default:
  }
}
